# Generated by Django 5.2.5 on 2025-08-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciais',
                'db_table': 'credenciais',
            },
        ),
    ]
